"""add foreign keys to transactions, phone, email

Revision ID: 2fa6f1f90c70
Revises: 191d00dccbcd
Create Date: 2023-11-30 19:24:24.194922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa6f1f90c70'
down_revision: Union[str, None] = '191d00dccbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'email', 'contractor', ['contractor_id'], ['contractor_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'phone', 'contractor', ['contractor_id'], ['contractor_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'contractor', ['contractor_id'], ['contractor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.drop_constraint(None, 'email', type_='foreignkey')
    # ### end Alembic commands ###
