"""add column producer to product

Revision ID: 445fc368d09b
Revises: fb961359753b
Create Date: 2023-11-29 11:42:44.111760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445fc368d09b'
down_revision: Union[str, None] = 'fb961359753b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('producer', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'producer')
    # ### end Alembic commands ###
