"""product_id is storage primary key

Revision ID: 57d7beb24f3b
Revises: 876f791e1ce7
Create Date: 2023-12-10 19:58:36.400635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d7beb24f3b'
down_revision: Union[str, None] = '876f791e1ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'storage', ['product_id'])
    op.drop_column('storage', 'storage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('storage_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'storage', type_='unique')
    # ### end Alembic commands ###
