"""product_id is possession primary key

Revision ID: 876f791e1ce7
Revises: 4ad3e8eb030f
Create Date: 2023-12-10 19:53:18.941197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876f791e1ce7'
down_revision: Union[str, None] = '4ad3e8eb030f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'possession', ['product_id'])
    op.drop_column('possession', 'possession_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('possession', sa.Column('possession_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'possession', type_='unique')
    # ### end Alembic commands ###
